name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this solve? Is this related to a frustration?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like. Include example API usage if possible.
      placeholder: |
        ```python
        n = nb("report.md", title="Report")
        n.new_widget(data, option="value")
        ```
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - "New widget"
        - "Existing widget improvement"
        - "Plugin system"
        - "Core / config"
        - "Developer experience"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you've considered?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references.
